# 
site_name: 01_â–«ï¸ğŸ“š_Proyecto.solar
theme:
  name: material
  palette:
    primary: white
  features:
    - toc.integrate
    - content.code.annotate
plugins:
  - mkdocstrings
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
nav:

    - ğŸ“š Expediente: 
        - â¬œ Indice: Expediente/002_ğŸ“š Expediente_â¬œ Indice.md 
    - ğŸ§‘ Cliente: 
        - â¬œ Oferta: Expediente/110_ğŸ§‘ Cliente_â¬œ Oferta.md 
        - â¬œ Contrato Instalacion: Expediente/120_ğŸ§‘ Cliente_â¬œ Contrato Instalacion.md 
    - ğŸ¦ Ayuntamiento: 
        - â¬œ RepresentaciÃ³n ante la GMU: Expediente/220_ğŸ¦ Ayuntamiento_â¬œ RepresentaciÃ³n ante la GMU.md 
        - â¬œ DECLARACIÃ“N RESPONSABLE PARA EJECUCIÃ“N DE OBRAS: Expediente/221_ğŸ¦ Ayuntamiento_â¬œ DECLARACIÃ“N RESPONSABLE PARA EJECUCIÃ“N DE OBRAS.md 
        - â¬œ DeclaraciÃ³n Responsable de Obras: Expediente/221_ğŸ¦ Ayuntamiento_â¬œ DeclaraciÃ³n Responsable de Obras.md 
        - â¬œ Certificado tÃ©cnico de colegiaciÃ³n y habilitaciÃ³n: Expediente/222_ğŸ¦ Ayuntamiento_â¬œ Certificado tÃ©cnico de colegiaciÃ³n y habilitaciÃ³n.md 
        - â¬œ Formulario normalizado Licencias de Obras: Expediente/225_ğŸ¦ Ayuntamiento_â¬œ Formulario normalizado Licencias de Obras.md 
        - â¬œ Panel o cartel informativo: Expediente/227_ğŸ¦ Ayuntamiento_â¬œ Panel o cartel informativo.md 
    - ğŸ“ Proyecto: 
        - â¬œ Memoria TÃ©cnica de DiseÃ±o: Expediente/230_ğŸ“ Proyecto_â¬œ Memoria TÃ©cnica de DiseÃ±o.md 
        - â¬œ Memoria: Expediente/240_ğŸ“ Proyecto_â¬œ Memoria.md 
        - â¬œ Planos: Expediente/260_ğŸ“ Proyecto_â¬œ Planos.md 
        - â¬œ Mediciones y presupuesto: Expediente/270_ğŸ“ Proyecto_â¬œ Mediciones y presupuesto.md 
        - â¬œ Certificado de instalaciÃ³n elÃ©ctrica: Expediente/290_ğŸ“ Proyecto_â¬œ Certificado de instalaciÃ³n elÃ©ctrica.md 
    - ğŸ‡ªğŸ‡º NextGenerationEU: 
        - â¬œ  DECLARACIÃ“N RESPONSABLE relativa a la estimaciÃ³n de que elconsumo: Expediente/320_ğŸ‡ªğŸ‡º NextGenerationEU_â¬œ  DECLARACIÃ“N RESPONSABLE relativa a la estimaciÃ³n de que elconsumo.md 
        - â¬œ  INFORME JUSTIFICATIVO de la previsiÃ³n del consumo anual: Expediente/320_ğŸ‡ªğŸ‡º NextGenerationEU_â¬œ  INFORME JUSTIFICATIVO de la previsiÃ³n del consumo anual.md 
        - â¬œ  OTORGAMIENTO DE LA REPRESENTACIÃ“N A LA EMPRESA ADHERIDA : Expediente/320_ğŸ‡ªğŸ‡º NextGenerationEU_â¬œ  OTORGAMIENTO DE LA REPRESENTACIÃ“N A LA EMPRESA ADHERIDA .md 
        - â¬œ DATOS TÃ‰CNICOS Y ECONÃ“MICOS REQUERIDOS PARA CADA PROGRAMA DE INCENTIVOS: Expediente/320_ğŸ‡ªğŸ‡º NextGenerationEU_â¬œ DATOS TÃ‰CNICOS Y ECONÃ“MICOS REQUERIDOS PARA CADA PROGRAMA DE INCENTIVOS.md 
    - ğŸ§ª Pruebas: 
        - â¬œ Admissions Application: Expediente/999_ğŸ§ª Pruebas_â¬œ Admissions Application.md 
        - â¬œ DECLARACION PROVEEDOR ALMACENAMIENTO Autoconsumo y termicas: Expediente/999_ğŸ§ª Pruebas_â¬œ DECLARACION PROVEEDOR ALMACENAMIENTO Autoconsumo y termicas.md 
        - â¬œ Estudio BÃ¡sico de Seguridad y Salud, telegramv1: Expediente/999_ğŸ§ª Pruebas_â¬œ Estudio BÃ¡sico de Seguridad y Salud, telegramv1.md 
        - â¬œNO  AFECCION  A OBJETIVOS MEDIOAMBIENTALES: Expediente/999_ğŸ§ª Pruebas_â¬œNO  AFECCION  A OBJETIVOS MEDIOAMBIENTALES.md
            