# 
site_name: 01_â–«ï¸ğŸ“š_Proyecto.solar
theme:
  name: material
  palette:
    primary: white
  features:
    - toc.integrate
    - content.code.annotate
plugins:
  - mkdocstrings
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
nav:

    - â¬œâ¬œâ¬œIndice.pdf: Expediente/002000000â¬œâ¬œâ¬œâ¬œIndice.md 
    - ğŸ§‘â¬œâ¬œ Oferta.pdf: Expediente/110100000ğŸŸ¥ğŸ§‘â¬œâ¬œ Oferta.md 
    - ğŸ§‘â¬œâ¬œ Contrato Instalacion.pdf: Expediente/120100000â¬œğŸ§‘â¬œâ¬œ Contrato Instalacion.md 
    - ğŸ¦â¬œâ¬œ RepresentaciÃ³n ante la GMU.pdf: Expediente/220290672â¬œğŸ¦â¬œâ¬œ RepresentaciÃ³n ante la GMU.md 
    - ğŸ¦ğŸ”§â¬œ DeclaraciÃ³n Responsable de Obras.pdf: Expediente/221290672â¬œğŸ¦ğŸ”§â¬œ DeclaraciÃ³n Responsable de Obras.md 
    - ğŸ¦ğŸ› â¬œ Certificado tÃ©cnico de colegiaciÃ³n y habilitaciÃ³n.pdf: Expediente/222290672â¬œğŸ¦ğŸ› â¬œ Certificado tÃ©cnico de colegiaciÃ³n y habilitaciÃ³n.md 
    - ğŸ¦ğŸ”¨â¬œ Formulario normalizado Licencias de Obras.pdf: Expediente/225290672â¬œğŸ¦ğŸ”¨â¬œ Formulario normalizado Licencias de Obras.md 
    - ğŸ¦ğŸ”¨â¬œ Panel o cartel informativo.pdf: Expediente/227290672â¬œğŸ¦ğŸ”¨â¬œ Panel o cartel informativo.md 
    - ğŸ“â¬œâ¬œ Memoria TÃ©cnica de DiseÃ±o.pdf: Expediente/230290672ğŸŸ¥ğŸ“â¬œâ¬œ Memoria TÃ©cnica de DiseÃ±o.md 
    - ğŸ“â¬œâ¬œ Memoria.pdf: Expediente/240290672ğŸŸ¥ğŸ“â¬œâ¬œ Memoria.md 
    - ğŸ“ğŸ—ºâ¬œ Planos.pdf: Expediente/260290672ğŸŸ¥ğŸ“ğŸ—ºâ¬œ Planos.md 
    - ğŸ“â¬œâ¬œ Mediciones y presupuesto.pdf: Expediente/270290672ğŸŸ¥ğŸ“â¬œâ¬œ Mediciones y presupuesto.md 
    - ğŸ“â¬œâ¬œ Certificado de instalaciÃ³n elÃ©ctrica.pdf: Expediente/290290672ğŸŸ¥ğŸ“â¬œâ¬œ Certificado de instalaciÃ³n elÃ©ctrica.md
            