# 
site_name: 01_â–«ï¸ğŸ“š_Proyecto.solar
docs_dir: 'docs_jpg'
theme:
  name: material
  palette:
    primary: white
  features:
    - toc.integrate
    - content.code.annotate
plugins:
  - mkdocstrings
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  

nav:

    - ğŸ“š Expediente: 
        - â¬œ Indice: Expediente/002_ğŸ“š Expediente_â¬œ Indice.md 
    - ğŸ§‘ Cliente: 
        - ğŸ§‘â¬œ Oferta: Expediente/110_ğŸ§‘ Cliente_ğŸ§‘â¬œ Oferta.md 
        - ğŸ§‘â¬œ formularioUnico: Expediente/110_ğŸ§‘ Cliente_ğŸ§‘â¬œ formularioUnico.md 
        - ğŸ§‘â¬œ Contrato: Expediente/120_ğŸ§‘ Cliente_ğŸ§‘â¬œ Contrato.md 
        - ğŸ§‘â¬œ SolicitudRegistrada: Expediente/120_ğŸ§‘ Cliente_ğŸ§‘â¬œ SolicitudRegistrada.md 
    - ğŸ¦ Ayuntamiento: 
        - ğŸ¦â¬œ RepresentaciÃ³n ante la GMU: Expediente/220_ğŸ¦ Ayuntamiento_ğŸ¦â¬œ RepresentaciÃ³n ante la GMU.md 
        - ğŸ¦â¬œ DECLARACIÃ“N RESPONSABLE PARA EJECUCIÃ“N DE OBRAS: Expediente/221_ğŸ¦ Ayuntamiento_ğŸ¦â¬œ DECLARACIÃ“N RESPONSABLE PARA EJECUCIÃ“N DE OBRAS.md 
        - ğŸ¦â¬œ DeclaraciÃ³n Responsable de Obras: Expediente/221_ğŸ¦ Ayuntamiento_ğŸ¦â¬œ DeclaraciÃ³n Responsable de Obras.md 
        - ğŸ¦â¬œ Certificado tÃ©cnico de colegiaciÃ³n y habilitaciÃ³n: Expediente/222_ğŸ¦ Ayuntamiento_ğŸ¦â¬œ Certificado tÃ©cnico de colegiaciÃ³n y habilitaciÃ³n.md 
        - ğŸ¦â¬œ Formulario normalizado Licencias de Obras: Expediente/225_ğŸ¦ Ayuntamiento_ğŸ¦â¬œ Formulario normalizado Licencias de Obras.md 
        - ğŸ¦â¬œ Panel o cartel informativo: Expediente/227_ğŸ¦ Ayuntamiento_ğŸ¦â¬œ Panel o cartel informativo.md 
    - ğŸ“ Proyecto: 
        - ğŸ“â¬œ Memoria TÃ©cnica de DiseÃ±o: Expediente/230_ğŸ“ Proyecto_ğŸ“â¬œ Memoria TÃ©cnica de DiseÃ±o.md 
        - ğŸ“â¬œ Memoria: Expediente/240_ğŸ“ Proyecto_ğŸ“â¬œ Memoria.md 
        - ğŸ“â¬œ Planos: Expediente/260_ğŸ“ Proyecto_ğŸ“â¬œ Planos.md 
        - ğŸ“ğŸ—º P SituaciÃ³n - Emplazamiento: Expediente/261_ğŸ“ Proyecto_ğŸ“ğŸ—º P SituaciÃ³n - Emplazamiento.md 
        - ğŸ“ğŸ—º P Plantas - Alzados.: Expediente/262_ğŸ“ Proyecto_ğŸ“ğŸ—º P Plantas - Alzados..md 
        - ğŸ“â¬œ Mediciones y presupuesto: Expediente/270_ğŸ“ Proyecto_ğŸ“â¬œ Mediciones y presupuesto.md 
        - ğŸ“â¬œ Certificado de instalaciÃ³n elÃ©ctrica: Expediente/290_ğŸ“ Proyecto_ğŸ“â¬œ Certificado de instalaciÃ³n elÃ©ctrica.md 
    - ğŸ‡ªğŸ‡º NextGenerationEU: 
        - ğŸ‡ªğŸ‡ºâ¬œ  DECLARACIÃ“N RESPONSABLE relativa a la estimaciÃ³n del consumoxx: Expediente/320_ğŸ‡ªğŸ‡º NextGenerationEU_ğŸ‡ªğŸ‡ºâ¬œ  DECLARACIÃ“N RESPONSABLE relativa a la estimaciÃ³n del consumoxx.md 
        - ğŸ‡ªğŸ‡ºâ¬œ  INFORME JUSTIFICATIVO de la previsiÃ³n del consumo anual: Expediente/320_ğŸ‡ªğŸ‡º NextGenerationEU_ğŸ‡ªğŸ‡ºâ¬œ  INFORME JUSTIFICATIVO de la previsiÃ³n del consumo anual.md 
        - ğŸ‡ªğŸ‡ºâ¬œ  OTORGAMIENTO DE LA REPRESENTACIÃ“N A LA EMPRESA ADHERIDA : Expediente/320_ğŸ‡ªğŸ‡º NextGenerationEU_ğŸ‡ªğŸ‡ºâ¬œ  OTORGAMIENTO DE LA REPRESENTACIÃ“N A LA EMPRESA ADHERIDA .md 
        - ğŸ‡ªğŸ‡ºâ¬œ DATOS TÃ‰CNICOS Y ECONÃ“MICOS REQUERIDOS PARA CADA PROGRAMA DE INCENTIVOS: Expediente/320_ğŸ‡ªğŸ‡º NextGenerationEU_ğŸ‡ªğŸ‡ºâ¬œ DATOS TÃ‰CNICOS Y ECONÃ“MICOS REQUERIDOS PARA CADA PROGRAMA DE INCENTIVOS.md 
        - ğŸ‡ªğŸ‡ºâ¬œautoconsumo declaracion sistema almacenamiento: Expediente/320_ğŸ‡ªğŸ‡º NextGenerationEU_ğŸ‡ªğŸ‡ºâ¬œautoconsumo declaracion sistema almacenamiento.md 
        - ğŸ‡ªğŸ‡ºâ¬œautoconsumo solicitud declaracion responsable 80: Expediente/320_ğŸ‡ªğŸ‡º NextGenerationEU_ğŸ‡ªğŸ‡ºâ¬œautoconsumo solicitud declaracion responsable 80.md 
    - ğŸ§ª Pruebas: 
        - ğŸ§ªâ¬œ Admissions Application: Expediente/999_ğŸ§ª Pruebas_ğŸ§ªâ¬œ Admissions Application.md 
        - ğŸ§ªâ¬œ DECLARACION PROVEEDOR ALMACENAMIENTO Autoconsumo y termicas: Expediente/999_ğŸ§ª Pruebas_ğŸ§ªâ¬œ DECLARACION PROVEEDOR ALMACENAMIENTO Autoconsumo y termicas.md 
        - ğŸ§ªâ¬œ Estudio BÃ¡sico de Seguridad y Salud, telegramv1: Expediente/999_ğŸ§ª Pruebas_ğŸ§ªâ¬œ Estudio BÃ¡sico de Seguridad y Salud, telegramv1.md 
        - ğŸ§ªâ¬œNO  AFECCION  A OBJETIVOS MEDIOAMBIENTALES: Expediente/999_ğŸ§ª Pruebas_ğŸ§ªâ¬œNO  AFECCION  A OBJETIVOS MEDIOAMBIENTALES.md
            